import type { Theme } from '@mui/material';

export default {
  cover: (theme: Theme, img: string) => ({
    display: 'flex',
    WebkitBoxAlign: 'center',
    alignItems: 'center',
    position: 'relative',
    minHeight: '14.75rem',
    opacity: '1',
    color: 'rgb(52, 71, 103)',
    background: `linear-gradient(310deg, rgb(32, 101, 209, 0.6),  rgb(32, 101, 209, 0.3)) 50% center / cover, url("${img}") transparent`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    borderRadius: '1rem',
    borderTopLeftRadius: { xs: 0, lg: '1rem' },
    borderTopRightRadius: { xs: 0, lg: '1rem' },
    backgroundPosition: '50% center',
    overflow: 'hidden',
  }),
  infoBox: {
    color: 'rgba(0, 0, 0, 0.87)',
    transition: 'box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minWidth: '0px',
    overflowWrap: 'break-word',
    backgroundClip: 'border-box',
    border: '0px solid rgba(0, 0, 0, 0.125)',
    borderRadius: '1rem',
    backdropFilter: 'saturate(200%) blur(30px)',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    boxShadow:
      'rgba(255, 255, 255, 0.9) 0rem 0rem 0.0625rem 0.0625rem inset, rgba(0, 0, 0, 0.05) 0rem 1.25rem 1.6875rem 0rem',
    position: 'relative',
    marginTop: { xs: -12, md: -8 },
    mx: { xs: 2, md: 3 },
    p: 2,
  },
  avatar: {
    width: '4.625rem',
    height: '4.625rem',
    borderRadius: '0.75rem',
  },
  nickname: {
    margin: '0px',
    fontSize: '1.25rem',
    lineHeight: 1.375,
    textTransform: 'none',
    verticalAlign: 'unset',
    textDecoration: 'none',
    color: 'rgb(52, 71, 103)',
    fontWeight: '500',
  },
  desc: {
    margin: '0px',
    fontSize: '0.875rem',
    lineHeight: '1.5',
    letterSpacing: '0.02857em',
    opacity: '1',
    textTransform: 'none',
    verticalAlign: 'unset',
    textDecoration: 'none',
    color: 'rgb(103, 116, 142)',
    fontWeight: '500',
  },
  // 标签样式
  tabs: {
    width: '100%',
    position: 'relative',
    zIndex: 100,

    '& .MuiTabs-indicator': {
      zIndex: -1,
      bottom: '0px',
      width: '100%',
      height: '100%',
      borderRadius: '0.5rem',
      backgroundColor: 'rgb(255, 255, 255)',
      transition: 'all 500ms ease 0s',
    },
  },
};
